### ISSUE TITLE
réponse "Je ne sais pas"

### ISSUE THREAD

**Issue by urosselet** [HEG-Arc/PrestaSoc#24]
Pour les situations où la personne touche des prestations d'aide mais ne peut pas nous dire lesquelles. 
Comment les prendre en comptes?

**Comment by sbridji** [comment]
Question difficile !
La seule chose qu'on puisse faire me semble-t-il est de faire les calculs sans prendre en compte les aides inconnues et d'ajouter un warning au résultat précisant que les calculs ont été fait sur la base des informations disponibles et inviter la personne à refaire l'estimation quand il saura quelles prestations il a perçu.
