### ISSUE TITLE
Remarques sur le site internet

### ISSUE THREAD

**Issue by sbridji** [HEG-Arc/PrestaSoc#26]
- Dans le fichier base/personne.html l. 7 : je demanderais la date de naissance plutôt que l'âge. Cela pourrait être utile pour les cas où ce qui comptera sera l'âge atteint durant l'année de référence plutôt que l'âge au moment de la demande.

- Dans le fichier base/personne.html l. 54 : je perlerais de bénéficiaire de l'aide sociale étant donné que le RI est spécifique au canton de Vaud. Peut-être que faut-il faire la modification dans la page https://script.google.com/macros/s/AKfycbxxtYoEsXArEobqe3Egs5-kWHawM45IggQYLczhUbcELDYg7Ag/exec exécutée par le fichier /services/variables.js : Mettre "personne.estBeneficiaireAideSociale":{"nomFR":"Bénéficiaire de l'aide sociale","helpVD":"","helpNE":"","helpGE":""} à la place de "personne.estBeneficiaireRI":{"nomFR":"Bénéficiaire d'un revenu d'insertion (RI)","helpVD":"","helpNE":"","helpGE":""}

- Dans le fichier base/personne.html l. 53 :  je préciserais à quelles prestations complémentaires nous faisons référence (PC AVS/AI ? PC fédéraux ?). Par exemple dans la page https://script.google.com/macros/s/AKfycbxxtYoEsXArEobqe3Egs5-kWHawM45IggQYLczhUbcELDYg7Ag/exec exécutée par le fichier /services/variables.js : "personne.estBeneficiairePC":{"nomFR":"Bénéficiaire de prestations complémentaires fédéraux à l'AVS ou AI","helpVD":"","helpNE":"","helpGE":""} à la place de "personne.estBeneficiairePC":{"nomFR":"Bénéficiaire de prestations complémentaires","helpVD":"","helpNE":"","helpGE":""}

**Comment by cgaspoz** [comment]
- Non pris en compte
- Corrigé suite à l'affichage multi-choix
- Corrigé suite à l'affichage multi-choix
