### ISSUE TITLE
Vous ou prénom pour la première personne

### ISSUE THREAD

**Issue by jotabin** [HEG-Arc/PrestaSoc#29]
– Je ne trouve pas user friendly le fait que "vous" soit inscrit en grisé sur la ligne où l'on va entrer son prénom (il faut sélectionner et taper dessus)
– Apparaît sur la page "Vous êtes" et "Vous recevez", sans autre indication, pourquoi ?

(navigateur Safari 10.0.3)

**Comment by cgaspoz** [comment]
On supprime le vous et on laisse le champ prénom vide
S'il n'est pas rempli on met un vous par défaut
