### ISSUE TITLE
Bug input number safari?

### ISSUE THREAD

**Issue by jotabin** [HEG-Arc/PrestaSoc#32]
Impossible d'entrer des données sous Votre revenu et Rentes et pensions dans Safari. Ok dans Chrome et Firefox.

**Comment by sbridji** [comment]
Si ça peut aider à réparer le bug : Cela dépend peut être de la version de Safari car ça semble fonctionner chez moi (Version 10.0.3 (10602.4.8.0.1))

**Comment by jotabin** [comment]
Erreurs console safari

[Error] Failed to load resource: the server responded with a status of 405 (HTTP/2.0 405) (echo, line 0)
[Error] Failed to load resource: Preflight response is not successful (echo, line 0)
[Error] XMLHttpRequest cannot load https://script.googleusercontent.com/macros/echo?user_content_key=d8skid3w7Q7628JZUeoSz_D_3SqnIa2YYRFwlMUby9dqzK0Jk0vmGyqHN_KRkLT6DkRPG5337BMaxmqu_zsN1s7qyHAxU05fm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnEyxudzYQhhSrnKgVeYgJ6vgzpxQq3WMQDnJKnafENwtBJ_nlX-mjm7Ajodihe7ko9veWPraiRQB&lib=MNwnmWXpqRzANxW_zx9TCcLJdggowjHzF. Preflight response is not successful
[Error] Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"https://script.google.com/macros/s/AKfycbxxtYoEsXArEobqe3Egs5-kWHawM45IggQYLczhUbcELDYg7Ag/exec","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":""} – undefined
	(fonction anonyme) (vendor-d1d6d37f7107dce6a3f8.js:1:1817)
	(fonction anonyme) (vendor-d1d6d37f7107dce6a3f8.js:39:17236)
	(fonction anonyme) (app-d1d6d37f7107dce6a3f8.js:7:10486)
	u (vendor-d1d6d37f7107dce6a3f8.js:40:6052)
	$digest (vendor-d1d6d37f7107dce6a3f8.js:40:11851)
	$apply (vendor-d1d6d37f7107dce6a3f8.js:40:13684)
	c (vendor-d1d6d37f7107dce6a3f8.js:39:21124)
	b (vendor-d1d6d37f7107dce6a3f8.js:39:23528)
	w (vendor-d1d6d37f7107dce6a3f8.js:39:23989)
	r (vendor-d1d6d37f7107dce6a3f8.js:1:7608)

**Comment by bfritscher** [comment]
Testé sur macOS 10.12.3 (Version 10.0.3 (10602.4.8))

le message semble indiquer un problème de chargement du fichier des textes d'aides.

**Comment by bfritscher** [comment]
Le fichier variable est maintenant chargé directement depuis le serveur pour éviter les appels jsonp et cors.
