### ISSUE TITLE
ajouter encore après En attendant l'ouverture du site, vous pouvez déjà tester vos droits à certaines prestations sociales si vous habitez dans les cantons de Neuchâtel, Vaud et Genève.

### ISSUE THREAD

**Issue by jotabin** [HEG-Arc/PrestaSoc#63]
Attention, ce site, créé début 2017, est encore en construction: les estimations ne sont pas finalisées!

**Comment by urosselet** [comment]
ajouté sur la page d'accueil (voir version "dev" du site) #60
