### ISSUE TITLE
Ajout dans le calcul du RDU pour les subsides dans le canton de Vaud

### ISSUE THREAD

**Issue by sbridji** [HEG-Arc/PrestaSoc#8]
Selon l'art. 3 al. 2 du RLHPS les PC pour famille et la rente pont doivent être pris en compte dans le calcul du RDU pour le subside de l'assurance maladie.
Donc, sauf erreur de ma part, il faudrait ajouter ces éléments là dans le calcul du RDU pour le subside dans le fichier /src/app/lamal/calcule.js.

**Comment by urosselet** [comment]
toutes ces rentes sont inclues dans le calcul du revenu net imposable au chiffre 195 de la DI.

**Comment by urosselet** [comment]
My bad. il faut quand même modifier le calcul du RDU: en relisant la loi : "Les prestations complémentaires au sens de la loi sur les prestations complémentaires pour familles et les prestations cantonales de la rente-pont ne sont pas prises en compte pour le calcul du revenu déterminant, à l’exception de celui pour les subsides aux primes d’assurance-maladie et les prestations d’aide et de maintien à domicile au sens de l’article 4a de la loi sur l’aide aux personnes recourant à l’action médico-sociale."
pour le moment, le calculateur RDU ne corrige pas les PC et la rente pont.

**Comment by urosselet** [comment]
75d2de4ab80d29c383a74f093864479f8c8fffb7

**Comment by sbridji** [comment]
Si j'ai bien compris, dans le calcul du RDU, il faut soustraire du revenu net imposable les montants de la rente pont et/ou des PC Familles perçues (qui ont été pris en compte dans le calcul du revenu imposable), ceci pour toutes les prestations sociales soumises à la LHPS sauf les subsides de l'assurance maladie.
Cependant, je pense qu'il faut qu'on soit au clair sur les questions de temporalité. Le revenu net imposable est à priori déterminé pour l'année N-1, N étant l'année courante. Donc, si je ne me trompe pas, il faudrait soustraire du revenu imposable la rente pont et les PC Fam perçues l'année N-1. Mais dans le fichier /src/app/finance/revenu.html les informations sur les revenus demandés (hors revenu imposable) sont-elles celles de l'année N ou N-1 ? Si c'est l'année N, il faudrait aussi demander la rente pont et PC Fam perçues l'année N-1 pour faire la correction sur le RDU. En effet, si la personne requérante perçoit une rente pont pour la première fois l'année courante N, on risque de soustraire du revenu imposable un montant qui n'avait pas été pris en compte dans le calcul du revenu imposable (rente pont non perçue l'année N-1).

**Comment by urosselet** [comment]
Hello Slim,
oui tout à fait, il faut que nous clarifions les questions de temporalité.
Puisqu'on est dans le cas d'une estimation et qu'en plus, les gens
remplissent le questionnaire eux-même, il faudrait expliciter cela le plus
clairement possible pour avoir une estimation la plus précise possible.
Toutefois, j'ai peur que d'introduire des notions d'années N et N-1 dans
les descriptions des champs rendent le remplissage du formulaire rébarbatif
voire trop difficile.
Evidemment, le but n'est pas de décourager les gens qui viennent sur le
site. Idéalement, qqn qui n'a pas de DI ou de DT devrait aussi pouvoir
l'utiliser.

Du coup, je propose qu'on clarifie ça dans le texte d'intro à la partie de
récolte des informations financières :
https://github.com/HEG-Arc/PrestaSoc/blob/master/src/app/base/statut.html
Est-ce que tu aurais une idée de la façon dont nous pourrions expliquer
cela simplement?
Par exemple: "Toutes les informations financières que vous saisissez
doivent se rapporter à la même période, typiquement la dernière année pour
laquelle vous avez reçu une décision taxation ou rempli une déclaration
d'impôt."
Merci pour tes commentaires,
Ulysse

**Comment by sbridji** [comment]
Salut Ulysse,

Je ne suis pas sûr que toutes les informations sur les revenus que nous allons demandés vont se rapporter à la même période. Je pense notamment au cas du canton de Genève où les subsides à l'assurance maladie et les avances sur pensions alimentaires se réfèrent aux revenus d'il y a deux ans, ce qui n'est pas le cas pour les autres prestations sociales. De même, en ce qui concerne les bourses d'études, les ressources des parents pris en compte sont le plus souvent celles de la dernière déclaration fiscale alors que les ressources de la personne formation requérante sont celles attendues durant l'année de formation (de septembre à août de l'année suivante). De même que pour les personnes qui ne sont pas soumis à la déclaration fiscale, je ne sais pas quelle temporalité ils utilisent. Dans les lois ça ne me semble pas précisé. A priori j'aurais tendance à penser qu'ils se basent sur les derniers revenus mais c'est à vérifier. Donc préciser tout ça dans le texte d'intro me semble compliquer vue la diversité des cas cantonaux... à moins d'avoir une intro spécifique à chaque canton.

Si ma crainte est juste - la temporalité peut changer d'un canton à l'autre voire d'une prestation à l'autre - je suggérerais quand même d'indiquer l'année de référence. Mais je suis d'accord qu'utiliser les concepts N, N-1 ou N+1 n'est pas judicieux. Peut être pourrions nous utiliser ces concepts dans le code mais en les rendant intelligibles à l'écran avec les fonctions de date automatique de JS. Du genre : 
```
var date = new Date(); // date courante
var Y = date.getFullYear(); // Année courante N
var Yb = Y-1 // Année précédente N-1
var Yf = Y+1 // Année prochaine N+1
```

Puis associer ces variables aux revenus demandés. 
Faudrait essayer pour voir ce que ça donne visuellement : lecture facile ou compliquée ?
Qu'en penses tu ?

Slim

**Comment by urosselet** [comment]
Oui c'est des possibilités intéressantes.
Toutefois, pour ce qui est du projet pilote, je pense que ça n'en vaut pas
la peine parce que ça complique beaucoup le processus de remplissage du
questionnaire et de collecte des données pour les bénéficiaires potentiels.
Ce qui va à l'encontre d'un de nos "arguments de vente" principal: la
simplicité d'utilisation et le fait d'avoir une estimation rapide.

Après, lorsque le projet sera financé, on se penchera à fond sur la
question et voir comment on gère ce problème.
ciao!
Ulysse
